
---
title: ""
author: ""
date: ""
output:
  github_document:
    toc: false
---


```{r,echo=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.path="inst/img/README-",
                      warning=FALSE,
                      fig.width=5, fig.height=5,message=FALSE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(Mmisc)
library(GGally)
library(pmplots)

df <- superset2() %>% filter(EVID==0)
```


# Table of contents
- [Basic functionality](#basics)
- Other examples
    - Complete listing: [everyfunction.md](inst/examples/everyfunction.md)
    - Other examples: [example1.md](inst/examples/example1.md)


<a name="basics"></a>

# Basics

## Simple function calls
```{r}
dv_pred(df, yname="NoDoze conc (ng/mL)")
```

## Add a title
```{r}
dv_time(df, title="Lookie here!")
```

## Modify the axes

```{r}
dv_time(df, xs=list(br=seq(0,240,24)))

dv_time(df, log=TRUE)

dv_time(df, yname="NoDoze (mg/L)",
        ys = list(trans="log", breaks=logbr()),
        xs = list(br=seq(0,240,72)))
```

## Some color support
```{r}
dv_time(df, col="STUDYc")
```

## Faceting
```{r}
dv_pred(df) + facet_wrap(~STUDY, ncol=2)
```

## Add theme
```{r}
dv_pred(df) + theme_plain()
```




